In [1]:
import pandas as pd
data = {
 'Order_ID': ['1001', '1002', '1003', '1004', '1005'],
 'Product_ID': ['P101', 'P102', 'P103', 'P101', 'P104'],
 'Product_Name': ['Laptop', 'Smartphone', 'Headphones', 'Laptop', 
'Coffee Maker'],
 'Category': ['Electronics', 'Electronics', 'Accessories', 
'Electronics', 'Kitchen'],
 'Quantity': [2, 1, 5, 3, 2],
 'Amount': [1600, 600, 500, 2400, 100],
 'Date': ['2024-01-10', '2024-01-11', '2024-01-12', '2024-01-12', 
'2024-01-13'],
 'Region': ['North', 'South', 'East', 'West', 'North'],
}
df_sales = pd.DataFrame(data)
df_sales

,Order_ID,Product_ID,Product_Name,Category,Quantity,Amount,Date,Region
0,1001,P101,Laptop,Electronics,2,1600,2024-01-10,North
1,1002,P102,Smartphone,Electronics,1,600,2024-01-11,South
2,1003,P103,Headphones,Accessories,5,500,2024-01-12,East
3,1004,P101,Laptop,Electronics,3,2400,2024-01-12,West
4,1005,P104,Coffee Maker,Kitchen,2,100,2024-01-13,North

In [11]:
ds = df_sales[((df_sales['Region'] == 'East') | (df_sales['Region'] == 'South')) & (df_sales['Amount'] >= 500)]
print(ds)

  Order_ID Product_ID Product_Name     Category  Quantity  Amount        Date  \
1     1002       P102   Smartphone  Electronics         1     600  2024-01-11
2     1003       P103   Headphones  Accessories         5     500  2024-01-12

  Region
1  South
2   East

In [12]:
sum_per_product = df_sales.groupby('Category')['Amount'].sum()
print(sum_per_product)

Category
Accessories     500
Electronics    4600
Kitchen         100
Name: Amount, dtype: int64

In [15]:
df_sales["Total_Amount"] = df_sales["Quantity"] * df_sales["Amount"]
df_sales["Tax"] = df_sales["Total_Amount"] * 0.15
df_sales["Net_Amount"] = df_sales["Total_Amount"] - df_sales["Tax"]
print(df_sales)

  Order_ID Product_ID  Product_Name     Category  Quantity  Amount  \
0     1001       P101        Laptop  Electronics         2    1600
1     1002       P102    Smartphone  Electronics         1     600
2     1003       P103    Headphones  Accessories         5     500
3     1004       P101        Laptop  Electronics         3    2400
4     1005       P104  Coffee Maker      Kitchen         2     100

         Date Region  total_sales_per_category  Total_Amount     Tax  \
0  2024-01-10  North                      3200          3200   480.0
1  2024-01-11  South                       600           600    90.0
2  2024-01-12   East                      2500          2500   375.0
3  2024-01-12   West                      7200          7200  1080.0
4  2024-01-13  North                       200           200    30.0

   Net_Amount
0      2720.0
1       510.0
2      2125.0
3      6120.0
4       170.0

In [16]:
df_sales["Date"] = pd.to_datetime(df_sales["Date"])
jan_10_11 = df_sales[
    (df_sales["Date"] >= "2024-01-10") &
    (df_sales["Date"] <= "2024-01-11")
]

print(jan_10_11)

  Order_ID Product_ID Product_Name     Category  Quantity  Amount       Date  \
0     1001       P101       Laptop  Electronics         2    1600 2024-01-10
1     1002       P102   Smartphone  Electronics         1     600 2024-01-11

  Region  total_sales_per_category  Total_Amount    Tax  Net_Amount
0  North                      3200          3200  480.0      2720.0
1  South                       600           600   90.0       510.0

In [17]:
import pandas as pd
data = {
 'Student_ID': ['S001', 'S002', 'S003', 'S004', 'S005'],
 'Mathematics' : [85, 75, 95, 65, 90],
 'Science' : [78, 88, 82, 85, 79],
 'English' : [90, 85, 80, 70, 95],
 'Information Technology' : [89, 65, 88, 92, 98]
}
df_result = pd.DataFrame(data)
df_result

  Student_ID  Mathematics  Science  English  Information Technology
0       S001           85       78       90                      89
1       S002           75       88       85                      65
2       S003           95       82       80                      88
3       S004           65       85       70                      92
4       S005           90       79       95                      98

In [18]:
import numpy as np
df_result['Average'] = np.mean(df_result[['Mathematics', 'Science', 
'English', 'Information Technology']], axis=1)
df_result

  Student_ID  Mathematics  Science  English  Information Technology  Average
0       S001           85       78       90                      89    85.50
1       S002           75       88       85                      65    78.25
2       S003           95       82       80                      88    86.25
3       S004           65       85       70                      92    78.00
4       S005           90       79       95                      98    90.50

In [20]:
df_result['Weighted Average'] = (df_result['Mathematics'] * 0.4) + \
(df_result['Science'] * 0.2) + (df_result['English'] * 0.2) + \
(df_result['Information Technology'] * 0.2)
df_result

,Student_ID,Mathematics,Science,English,Information Technology,Average,Weighted Average
0,S001,85,78,90,89,85.50,85.4
1,S002,75,88,85,65,78.25,77.6
2,S003,95,82,80,88,86.25,88.0
3,S004,65,85,70,92,78.00,75.4
4,S005,90,79,95,98,90.50,90.4

In [21]:
def standardize(column):
 mean = np.mean(column)
 std_dev = np.std(column)
 return (column - mean) / std_dev
# Standardize the columns
df_result['Math_Std'] = standardize(df_result['Mathematics'])
df_result['Sci_Std'] = standardize(df_result['Science'])
df_result['Eng_Std'] = standardize(df_result['English'])
df_result['IT_Std'] = standardize(df_result['Information Technology'])
df_result

,Student_ID,Mathematics,Science,English,Information Technology,Average,Weighted Average,Math_Std,Sci_Std,Eng_Std,IT_Std
0,S001,85,78,90,89,85.50,85.4,0.278543,-1.182727,0.697486,0.231040
1,S002,75,88,85,65,78.25,77.6,-0.649934,1.505289,0.116248,-1.901640
2,S003,95,82,80,88,86.25,88.0,1.207020,-0.107521,-0.464991,0.142179
3,S004,65,85,70,92,78.00,75.4,-1.578410,0.698884,-1.627467,0.497625
4,S005,90,79,95,98,90.50,90.4,0.742781,-0.913926,1.278724,1.030796

In [ ]:
def assign_grade(weighted_avg):
	if weighted_avg >= 85:
		return 'A'
	elif weighted_avg >= 75:
		return 'B'
	elif weighted_avg >= 65:
		return 'C'
	elif weighted_avg >= 55:
		return 'D'
	else:
		return 'F'

# Apply the grading function to the weighted averages
df_result['Final_Grade'] = df_result['Weighted Average'].apply(assign_grade)
df_result